<?php

namespace Mon\QcmBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ParticipationAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationAnswerRepository extends EntityRepository
{
}
